# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - ci-compose
    
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10-browsers
      # - environment: DBUS_SESSION_BUS_ADDRESS=/dev/null
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout
      
      # - run: sudo su -c 'echo "deb http://deb.debian.org/debian jessie-backports main" >> /etc/apt/sources.list'

      # - run: |
      #     sudo rm -rf /var/lib/apt/lists/*
      #     sudo apt-get update
      #     sudo apt install -t jessie-backports openjdk-8-jre-headless ca-certificates-java

      # - run:
      #     name: Update Chromedriver
      #     command: |
      #         wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      #         sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      #         sudo apt-get update
      #         sudo apt-get -y install google-chrome-stable

      # run tests!
      # - run: npm run e2e

      - setup_remote_docker:   
          docker_layer_caching: true 
      
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      
      - run:
          name: Start Container
          command: |
            docker-compose up -d
            docker-compose ps
      
      - run:
          docker exec -it project_backoffice_1 npm run e2e

      # # build and push Docker image
      # - run: |
      #     TAG=latest   
      #     docker login -u $DOCKER_USER -p $DOCKER_PASS         
      #     docker push wadman/circleci-demo-bo:$TAG

